version: "3.5"
name: knowledge-graphs
services:
  graphdb:
    container_name: kg-graphdb
    image: ontotext/graphdb:10.3.3
    ports:
      - "7202:7200"
      - "7301:7300"
    restart: unless-stopped
    command:
      - -Dgraphdb.home=/opt/graphdb/home
      - -Dgraphdb.workbench.cors.enable=true
      - -Dgraphdb.workbench.cors.origin=*
      - -Dgraphdb.append.request.id.headers=true
      - -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
      - -Dhealth.max.query.time.seconds=60
      - -Dreuse.vars.in.subselects=true
      - -Dgraphdb.external-url=https://kg.biocomputingup.it/graphdb/
    volumes:
      - kg-graphdb:/opt/graphdb/home

  virtuoso:
    container_name: kg-virtuoso
    image: tenforce/virtuoso:latest
    ports:
      - "8891:8890"
      - "1112:1111"
    restart: unless-stopped
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "https://idpcentral.org/registry/"
      DBA_PASSWORD: "dba"
    volumes:
      - kg-virtuoso:/data

volumes:
  kg-graphdb:
    external: true
    name: kg-graphdb
  kg-virtuoso:
    external: true
    name: kg-virtuoso
