version: "3.5"
name: idpregistry-kg
services:
  graphdb:
    container_name: idpregistry-graphdb
    image: ontotext/graphdb:10.3.3
    ports:
      - "7201:7200"
      - "7300:7300"
    restart: unless-stopped
    command:
      - -Dgraphdb.home=/opt/graphdb/home
      - -Dgraphdb.workbench.cors.enable=true
      - -Dgraphdb.workbench.cors.origin=*
      - -Dgraphdb.append.request.id.headers=true
      - -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
      - -Dhealth.max.query.time.seconds=60
      - -Dreuse.vars.in.subselects=true
      - -Dgraphdb.external-url=https://registry.idpcentral.org/graphdb
    volumes:
      - idpregistry-graphdb:/opt/graphdb/home

  virtuoso:
    container_name: idpregistry-virtuoso
    image: tenforce/virtuoso:latest
    ports:
      - "8890:8890"
      - "1111:1111"
    restart: unless-stopped
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "https://idpcentral.org/registry/"
      DBA_PASSWORD: "dba"
    volumes:
      - idpregistry-virtuoso:/data

volumes:
  idpregistry-graphdb:
    external: true
    name: idpregistry-graphdb
  idpregistry-virtuoso:
    external: true
    name: idpregistry-virtuoso
