# For each protein, check it's presence in the available dbs
PREFIX schema: <https://schema.org/>
PREFIX idp: <https://idpcentral.org/registry/>

SELECT ?proteinId (MAX(?mobidb) as ?mobi) (MAX(?ped) as ?ped) (MAX(?disprot) as ?disprot)
WHERE {
    {
        SELECT ?proteinId ?mobidb ?ped ?disprot
        WHERE {
            GRAPH ?g {
                ?x schema:sameAs ?proteinId .
            }
            BIND((?g = idp:ped) AS ?ped)
            BIND((?g = idp:disprot) AS ?disprot)
            BIND((?g = idp:mobidb) AS ?mobidb)

            {
                SELECT DISTINCT ?proteinId
                WHERE {
                    ?protein a schema:Protein ;
                        schema:sameAs ?proteinId .
                }
            }
        }
    }
}
GROUP BY ?proteinId
